// <auto-generated />
using System;
using Dingler.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dingler.Data.Migrations.GameData
{
    [DbContext(typeof(GameDataContext))]
    [Migration("20260329024238_ChangePlayerProfileIdToUlong")]
    partial class ChangePlayerProfileIdToUlong
    {
                protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Dingler.Data.Entities.GameData.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Email" }, "IX_Accounts_Email")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Dingler.Data.Entities.GameData.CardSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "IX_Set_Name")
                        .IsUnique();

                    b.ToTable("Set", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "ShardsOfFate"
                        },
                        new
                        {
                            Id = 2,
                            Name = "ShatteredDestiny"
                        },
                        new
                        {
                            Id = 3,
                            Name = "ArmiesOfMyth"
                        },
                        new
                        {
                            Id = 4,
                            Name = "PrimalDawn"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Herofall"
                        },
                        new
                        {
                            Id = 6,
                            Name = "ScarsOfWar"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Frostheart"
                        },
                        new
                        {
                            Id = 8,
                            Name = "DeadOfWinter"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Doombringer"
                        });
                });

            modelBuilder.Entity("Dingler.Data.Entities.GameData.Deck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChampionGuid")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("00000000-0000-0000-0000-000000000000");

                    b.Property<string>("DeckBitsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeckGuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeckName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("PlayerProfileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerProfileId");

                    b.HasIndex(new[] { "DeckGuid" }, "IX_Decks_DeckGuid")
                        .IsUnique();

                    b.HasIndex(new[] { "DeckName", "PlayerProfileId" }, "IX_Decks_DeckName_PlayerProfileId")
                        .IsUnique();

                    b.ToTable("Decks");
                });

            modelBuilder.Entity("Dingler.Data.Entities.GameData.DraftSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CardSetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TournamentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CardSetId");

                    b.HasIndex("TournamentId");

                    b.ToTable("DraftSets", (string)null);
                });

            modelBuilder.Entity("Dingler.Data.Entities.GameData.Friend", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FriendStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("RequestedId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("RequesterId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FriendStatusId");

                    b.HasIndex("RequestedId");

                    b.HasIndex(new[] { "RequesterId", "RequestedId" }, "IX_Friends_RequesterId_RequestedId")
                        .IsUnique();

                    b.ToTable("Friends");
                });

            modelBuilder.Entity("Dingler.Data.Entities.GameData.FriendStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Description" }, "IX_FriendStatus_Description")
                        .IsUnique();

                    b.ToTable("FriendStatus", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Accepted"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Blocked"
                        });
                });

            modelBuilder.Entity("Dingler.Data.Entities.GameData.MatchType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Description" }, "IX_MatchType_Description")
                        .IsUnique();

                    b.ToTable("MatchType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "SingleElimination"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Swiss"
                        },
                        new
                        {
                            Id = 3,
                            Description = "SwissWithTop8"
                        });
                });

            modelBuilder.Entity("Dingler.Data.Entities.GameData.PlayerProfile", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Elo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1000)
                        .HasColumnName("ELO");

                    b.Property<int>("RankId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasIndex("RankId");

                    b.HasIndex(new[] { "Username" }, "IX_PlayerProfiles_Username")
                        .IsUnique();

                    b.ToTable("PlayerProfiles");
                });

            modelBuilder.Entity("Dingler.Data.Entities.GameData.Rank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "IX_Rank_Name")
                        .IsUnique();

                    b.ToTable("Rank", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bronze"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Silver"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Gold"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Platinum"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Cosmic"
                        });
                });

            modelBuilder.Entity("Dingler.Data.Entities.GameData.StartCondition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Description" }, "IX_StartCondition_Description")
                        .IsUnique();

                    b.ToTable("StartCondition", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "WhenFull"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Scheduled"
                        });
                });

            modelBuilder.Entity("Dingler.Data.Entities.GameData.Tournament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MatchTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NeededPlayers")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StartConditionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TournamentTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MatchTypeId");

                    b.HasIndex("StartConditionId");

                    b.HasIndex("TournamentTypeId");

                    b.HasIndex(new[] { "Description" }, "IX_Tournament_Description")
                        .IsUnique();

                    b.ToTable("Tournaments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "1v1 Standard Match",
                            MatchTypeId = 1,
                            NeededPlayers = 2,
                            StartConditionId = 1,
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TournamentTypeId = 3
                        },
                        new
                        {
                            Id = 2,
                            Description = "1v1 Immortal Match",
                            MatchTypeId = 1,
                            NeededPlayers = 2,
                            StartConditionId = 1,
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TournamentTypeId = 4
                        });
                });

            modelBuilder.Entity("Dingler.Data.Entities.GameData.TournamentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "IX_TournamentType_Name")
                        .IsUnique();

                    b.ToTable("TournamentType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Draft"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sealed"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Standard"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Immortal"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Rock"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Iconoclast"
                        });
                });

            modelBuilder.Entity("Dingler.Data.Entities.GameData.Deck", b =>
                {
                    b.HasOne("Dingler.Data.Entities.GameData.PlayerProfile", "PlayerProfile")
                        .WithMany("Decks")
                        .HasForeignKey("PlayerProfileId")
                        .IsRequired();

                    b.Navigation("PlayerProfile");
                });

            modelBuilder.Entity("Dingler.Data.Entities.GameData.DraftSet", b =>
                {
                    b.HasOne("Dingler.Data.Entities.GameData.CardSet", "CardSet")
                        .WithMany("DraftSets")
                        .HasForeignKey("CardSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dingler.Data.Entities.GameData.Tournament", "Tournament")
                        .WithMany("DraftSets")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardSet");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("Dingler.Data.Entities.GameData.Friend", b =>
                {
                    b.HasOne("Dingler.Data.Entities.GameData.FriendStatus", "Status")
                        .WithMany("Friends")
                        .HasForeignKey("FriendStatusId")
                        .IsRequired();

                    b.HasOne("Dingler.Data.Entities.GameData.PlayerProfile", "Requested")
                        .WithMany("FriendRequesteds")
                        .HasForeignKey("RequestedId")
                        .IsRequired();

                    b.HasOne("Dingler.Data.Entities.GameData.PlayerProfile", "Requester")
                        .WithMany("FriendRequesters")
                        .HasForeignKey("RequesterId")
                        .IsRequired();

                    b.Navigation("Requested");

                    b.Navigation("Requester");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Dingler.Data.Entities.GameData.PlayerProfile", b =>
                {
                    b.HasOne("Dingler.Data.Entities.GameData.Account", "Account")
                        .WithOne("PlayerProfile")
                        .HasForeignKey("Dingler.Data.Entities.GameData.PlayerProfile", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dingler.Data.Entities.GameData.Rank", "Rank")
                        .WithMany("PlayerProfiles")
                        .HasForeignKey("RankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Rank");
                });

            modelBuilder.Entity("Dingler.Data.Entities.GameData.Tournament", b =>
                {
                    b.HasOne("Dingler.Data.Entities.GameData.MatchType", "MatchType")
                        .WithMany("Tournaments")
                        .HasForeignKey("MatchTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dingler.Data.Entities.GameData.StartCondition", "StartCondition")
                        .WithMany("Tournaments")
                        .HasForeignKey("StartConditionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dingler.Data.Entities.GameData.TournamentType", "TournamentType")
                        .WithMany("Tournaments")
                        .HasForeignKey("TournamentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MatchType");

                    b.Navigation("StartCondition");

                    b.Navigation("TournamentType");
                });

            modelBuilder.Entity("Dingler.Data.Entities.GameData.Account", b =>
                {
                    b.Navigation("PlayerProfile");
                });

            modelBuilder.Entity("Dingler.Data.Entities.GameData.CardSet", b =>
                {
                    b.Navigation("DraftSets");
                });

            modelBuilder.Entity("Dingler.Data.Entities.GameData.FriendStatus", b =>
                {
                    b.Navigation("Friends");
                });

            modelBuilder.Entity("Dingler.Data.Entities.GameData.MatchType", b =>
                {
                    b.Navigation("Tournaments");
                });

            modelBuilder.Entity("Dingler.Data.Entities.GameData.PlayerProfile", b =>
                {
                    b.Navigation("Decks");

                    b.Navigation("FriendRequesteds");

                    b.Navigation("FriendRequesters");
                });

            modelBuilder.Entity("Dingler.Data.Entities.GameData.Rank", b =>
                {
                    b.Navigation("PlayerProfiles");
                });

            modelBuilder.Entity("Dingler.Data.Entities.GameData.StartCondition", b =>
                {
                    b.Navigation("Tournaments");
                });

            modelBuilder.Entity("Dingler.Data.Entities.GameData.Tournament", b =>
                {
                    b.Navigation("DraftSets");
                });

            modelBuilder.Entity("Dingler.Data.Entities.GameData.TournamentType", b =>
                {
                    b.Navigation("Tournaments");
                });
#pragma warning restore 612, 618
        }
    }
}
