// <auto-generated />
using Dingler.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dingler.Data.Migrations.HexCredentials
{
    [DbContext(typeof(HexCredentialsContext))]
    [Migration("20260219184729_BaselineSchema")]
    partial class BaselineSchema
    {
                protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Dingler.Data.Entities.Credentials.BannableOffense", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Offense")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Offense" }, "IX_BannableOffenses_Offense")
                        .IsUnique();

                    b.ToTable("BannableOffenses");
                });

            modelBuilder.Entity("Dingler.Data.Entities.Credentials.BannedUser", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DateOfBan")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LengthOfBan")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OffenseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserCredentialsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OffenseId");

                    b.HasIndex(new[] { "UserCredentialsId" }, "IX_BannedUsers_UserCredentialsId")
                        .IsUnique();

                    b.ToTable("BannedUsers");
                });

            modelBuilder.Entity("Dingler.Data.Entities.Credentials.UserCredential", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Email" }, "IX_UserCredentials_Email")
                        .IsUnique();

                    b.ToTable("UserCredentials");
                });

            modelBuilder.Entity("Dingler.Data.Entities.Credentials.UserLoginAttempt", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FailedLoginCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LastFailedLogin")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LastSuccessfulLogin")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId" }, "IX_UserLoginAttempts_UserId")
                        .IsUnique();

                    b.ToTable("UserLoginAttempts");
                });

            modelBuilder.Entity("Dingler.Data.Entities.Credentials.BannedUser", b =>
                {
                    b.HasOne("Dingler.Data.Entities.Credentials.BannableOffense", "Offense")
                        .WithMany("BannedUsers")
                        .HasForeignKey("OffenseId")
                        .IsRequired();

                    b.HasOne("Dingler.Data.Entities.Credentials.UserCredential", "UserCredentials")
                        .WithOne("BannedUser")
                        .HasForeignKey("Dingler.Data.Entities.Credentials.BannedUser", "UserCredentialsId")
                        .IsRequired();

                    b.Navigation("Offense");

                    b.Navigation("UserCredentials");
                });

            modelBuilder.Entity("Dingler.Data.Entities.Credentials.UserLoginAttempt", b =>
                {
                    b.HasOne("Dingler.Data.Entities.Credentials.UserCredential", "User")
                        .WithOne("UserLoginAttempt")
                        .HasForeignKey("Dingler.Data.Entities.Credentials.UserLoginAttempt", "UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Dingler.Data.Entities.Credentials.BannableOffense", b =>
                {
                    b.Navigation("BannedUsers");
                });

            modelBuilder.Entity("Dingler.Data.Entities.Credentials.UserCredential", b =>
                {
                    b.Navigation("BannedUser");

                    b.Navigation("UserLoginAttempt");
                });
#pragma warning restore 612, 618
        }
    }
}
